### ISSUE TITLE
mod for V18?

### ISSUE THREAD

**Issue by turbocpt** [macmorning/itsm_mobileview#1]
Good Day. I am looking to use this for v18 instead of v8. But I am getting errors because of the change in the versions. Do you perhaps have anything that will be able use the Remedy API?

**Comment by macmorning** [comment]
Hello! Sorry I have not been maintaining this repo for years now. I am not aware of Remedy API recent evolutions, but I sure hope there is a better way of doing web applications with BMC Remedy nowadays.
